var weatherDescriptions = {
  '200': 'looking like a thunderstorm with light rain',
  '201': 'looking like a thunderstorm with rain',
  '202': 'looking like a thunderstorm with heavy rain',
  '210': 'looking like light thunderstorms',
  '211': 'looking like a thunderstorm',
  '212': 'looking like a heavy thunderstorm',
  '221': 'looking like a ragged thunderstorm',
  '230': 'looking like a thunderstorm with light drizzle',
  '231': 'looking like a thunderstorm with drizzle',
  '232': 'looking like a thunderstorm with heavy drizzle',
  '300': 'looking like a light intensity drizzle',
  '301': 'drizzling',
  '302': 'a heavy intensity drizzle rain',
  '310': 'looking like light intensity drizzle rain',
  '311': 'drizzling rain',
  '312': 'looking like heavy intensity drizzly rain',
  '321': 'drizzling',
  '500': 'looking like light rain',
  '501': 'looking like moderate rain',
  '502': 'looking like heavy intensity rain',
  '503': 'looking like a very heavy rain',
  '504': 'looking like extreme rain showers',
  '511': 'freezing rain',
  '520': 'looking like light rain showers',
  '521': 'raining',
  '522': 'raining quite heavily',
  '600': 'lightly snowing',
  '601': 'snowing',
  '602': 'snowing heavily',
  '611': 'looking like sleet',
  '621': 'showering snow',
  '701': 'quite misty',
  '711': 'smoky',
  '721': 'looking hazy',
  '731': 'looking dusty out there',
  '741': 'foggy',
  '800': 'a beautiful clear, sunny day',
  '801': 'a bit cloudy',
  '802': 'looking like scattered clouds',
  '803': 'broken clouds with the sun approaching',
  '804': 'very cloudy, looking like overcast',
  '900': 'a tornado warning',
  '901': 'a tropical storm',
  '902': 'a hurricane force wind',
  '903': 'cold ',
  '904': 'hot hot hot',
  '905': 'breezy',
  '906': 'hailing'
}

module.exports = weatherDescriptions;
